name: Deduplicate News

on:
  schedule:
    - cron: "*/10 * * * *" 
  workflow_dispatch: # Allows manual triggering

jobs:
  update-news:
    runs-on: ubuntu-latest
    steps:
      - name: Call Deduplicate News API
        run: |
          curl -X POST https://based.layzekid.com/api/dedupe