name: Update News

on:
  schedule:
    - cron: "0 0 * * *" # Runs once a day at midnight UTC
  workflow_dispatch: # Allows manual triggering

jobs:
  update-news:
    runs-on: ubuntu-latest
    steps:
      - name: Call Update News API
        run: |
          curl -X GET https://based.layzekid.com/api/news?updateAllVibes=true